---
{{- /*
Define a dynamic name for the Role based on the operation name and other properties.
This template handles different operation names and constructs a unique name accordingly.
*/ -}}
{{- define "argo-workflows-operations.dynamic-name" -}}
  {{- $fullBaseName := .operation.name -}}
  {{- $splitBaseName := splitList "-" $fullBaseName -}}
  {{- $baseName := index $splitBaseName 0 -}}
  {{- $namespaceName := .Release.Namespace -}}

  {{- if eq .operation.name "aks-start-stop-cluster" -}}
    {{ printf "%s-%s-%s" $baseName $namespaceName (.operation.inputs.cluster_name) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "flexible-server-start-stop-postgresql" -}}
    {{ printf "%s-%s-%s" $baseName $namespaceName (.operation.inputs.server_name) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.inputs.name "vmss-scale-instances" -}}
    {{ printf "%s-%s-%s" $baseName $namespaceName (.operation.inputs.vmss_name) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "mongodb-atlas-start-pause-cluster" -}}
    {{ printf "%s-%s-%s-%s" $baseName $namespaceName (.operation.inputs.project_id | trunc 6) (.operation.inputs.cluster_name) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "datadog-unmute-mute-monitors" -}}
    {{ printf "%s-%s-%s" $baseName $namespaceName (.operation.inputs.action) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "uptimerobot-resume-pause-monitors" -}}
    {{ printf "%s-%s-%s" $baseName $namespaceName (.operation.inputs.action) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "slack-notification" -}}
    {{ printf "%s-%s" $baseName $namespaceName | trunc 60 | replace "_" "-" | lower }}

  {{- else -}}
    {{ printf "%s-%s" $baseName $namespaceName | trunc 60 | replace "_" "-" }}
  {{- end -}}
{{- end -}}
