---
{{- /*
Define a dynamic name for the Role based on the operation name and other properties.
This template handles different operation names and constructs a unique name accordingly.
*/ -}}
{{- define "argo-workflows-operations.dynamic-name" -}}
  {{- $fullBaseName := .operation.name -}}
  {{- $splitBaseName := splitList "-" $fullBaseName -}}
  {{- $baseName := index $splitBaseName 0 -}}
  {{- $namespaceName := .Release.Namespace -}}
  {{- $environment := .Release.Namespace | splitList "-" | last -}}

  {{- if eq .operation.name "aks-start-stop-cluster" -}}
    {{ printf "%s-%s-%s-%s" $baseName $environment (.operation.inputs.cluster_name) (.operation.inputs.action) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "flexible-server-start-stop-postgresql" -}}
    {{ printf "%s-%s-%s-%s" $baseName $environment (.operation.inputs.server_name) (.operation.inputs.action) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "vmss-scale-instances" -}}
    {{ printf "%s-%s-%s-%d" $baseName $environment (.operation.inputs.vmss_name) (int (.operation.inputs.instances)) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "mongodb-atlas-start-pause-cluster" -}}
    {{ printf "%s-%s-%s-%s-%s" $baseName $environment (.operation.inputs.project_id | trunc 4) (.operation.inputs.cluster_name) (.operation.inputs.action) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "datadog-unmute-mute-monitors" -}}
    {{ printf "%s-%s-%s" $baseName $namespaceName (.operation.inputs.action) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "uptimerobot-resume-pause-monitors" -}}
    {{ printf "%s-%s-%s" $baseName $namespaceName (.operation.inputs.action) | trunc 60 | replace "_" "-" | lower }}

  {{- else if eq .operation.name "slack-notification" -}}
    {{- $concatOperations := "" -}}
    {{- range .operation.inputs.operations -}}
      {{- $splitOperation := splitList "-" . -}}
      {{- $lastWord := index $splitOperation (sub (len $splitOperation) 1) -}}
      {{- $concatOperations = print $concatOperations "-" $lastWord -}}
    {{- end -}}
    {{ printf "%s%s%s" $baseName $namespaceName $concatOperations | trunc 60 | replace "_" "-" | lower }}

  {{- if eq .operation.name "apply-patches-system-services-aks-to-datadog" -}}
    {{ printf "%s-%s-%s" $baseName $environment (.operation.inputs.cluster_name) | trunc 60 | replace "_" "-" | lower }}

  {{- else -}}
    {{ printf "%s-%s" $baseName $namespaceName | trunc 60 | replace "_" "-" }}
  {{- end -}}
{{- end -}}
