---
{{- /*
Define a dynamic name for the Role based on the feature name and other properties.
This template handles different feature names and constructs a unique name accordingly.
*/ -}}
{{- define "argo-workflows-operations.dynamic-name" -}}
  {{- $baseName := .feature.name | lower -}}
  {{- if eq .feature.name "aks-start-stop-cluster" -}}
    {{ printf "%s-%s-%s" $baseName (.feature.inputs.resource_group | lower) (.feature.inputs.cluster_name | lower) | trunc 60 | trimSuffix "-" }}
  {{- else if eq .feature.name "flexible-server-start-stop-postgresql" -}}
    {{ printf "%s-%s-%s" $baseName (.feature.inputs.resource_group | lower) (.feature.inputs.server_name | lower) | trunc 60 | trimSuffix "-" }}
  {{- else if eq .feature.inputs.name "vmss-scale-instances_count" -}}
    {{ printf "%s-%s-%s" $baseName (.feature.inputs.resource_group | lower) (.feature.inputs.vmss_name | lower) | trunc 60 | trimSuffix "-" }}
  {{- else if eq .feature.name "mongodb-atlas-start-pause-cluster" -}}
    {{ printf "%s-%s-%s" $baseName (.feature.inputs.project_id | lower) (.feature.inputs.cluster_name | lower) | trunc 60 | trimSuffix "-" }}
  {{- else -}}
    {{ $baseName }}
  {{- end -}}
{{- end }}
