---
{{- /*
Load the allowed operations from the values.yaml file.
*/ -}}
{{- $allowed_operations := .Values.allowed_operations -}}

{{- /*
Validate that the feature.name is one of the allowed values.
*/ -}}
{{- range .Values.operations }}
  {{- if not (has .name $allowed_operations) -}}
    {{- fail (printf "Feature name '%s' is not allowed. Allowed feature names are:\n- %s" .name (join "\n- " $allowed_operations)) -}}
  {{- end -}}
{{- end }}
