---
{{- /*
Define the rules for the Role resource for the argo-workflows-operations chart.
This template is called for each feature defined and fixes rules for the Role.
*/ -}}
{{ define "argo-workflows-operations.rules" }}

{{- if or (eq .feature.name "aks-start-stop-cluster") (eq .feature.name "flexible-server-start-stop-postgresql") (eq .feature.name "vmss-scale-instances_count") -}}
- apiGroups: [""]
  verbs: ["get", "list", "watch", "patch"]
  resources: ["pods", "pods/exec", "secrets"]
- apiGroups: ["firestartr.dev"]
  resources: ["terraformworkspaces"]
  verbs: ["get", "list", "watch"]
{{- end -}}

{{- if or (eq .feature.name "mongodb-atlas-start-pause-cluster") (eq .feature.name "datadog-unmute-mute-monitors") -}}
- apiGroups: [""]
  verbs: ["get", "watch", "list", "patch"]
  resources: ["pods", "pods/exec", "secrets"]
- apiGroups: ["firestartr.dev"]
  resources: ["terraformworkspaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ .feature.inputs.secret_name | quote }}]
  verbs: ["get"]
{{- end -}}

{{- end -}}

{{- /*
Define the Role resource for the argo-workflows-operations chart.
The name of the Role is dynamically generated using the "argo-workflows-operations.dynamic-name" template.
*/ -}}
{{ define "argo-workflows-operations.role" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argo-workflows-operations.dynamic-name" . }}-r
  namespace: {{ .Release.Namespace }}
rules:
{{ include "argo-workflows-operations.rules" . | indent 2 }}
{{ end }}

{{- /*
Iterate over the operations defined in the values file and create a Role for each feature.
The root context and the current feature are passed to the "argo-workflows-operations.role" template.
*/ -}}
{{- $root := . -}}
{{- range .Values.operations }}
  {{- include "argo-workflows-operations.role" (dict "root" $root "feature" . "Release" $root.Release "Values" $root.Values "global" $root.Values.global) -}}
{{- end }}