{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak.serviceAccountName" . }}
  {{ $length := len .Values.serviceAccount.annotations }}
  {{- if or (eq $length 0)  (eq .Values.parameterStore.enabled true)}}
  annotations:
    {{- if .Values.parameterStore.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.parameterStore.secrets_scm_sa_arn }}
    {{ end }}
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.serviceAccount.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
imagePullSecrets:
  {{- toYaml .Values.serviceAccount.imagePullSecrets | nindent 4 }}
{{- end }}
