---
{{- define "base.utiles.listado_ips_proxy" -}}

{{- $render := false }}
{{- $ips := (list) }}

{{- $enabled := true }}

{{- if hasKey .Values.whitelist "enabled" -}}
{{- $enabled = .Values.whitelist.enabled -}}
{{ end }}

{{- if $enabled -}} 
{{- $ips = (concat $ips .Values.whitelist.ips) -}}
{{- $render = true -}}
{{- end -}}

{{- if $enabled -}} 
{{- $render = true -}}
{{- end -}}
{{- $ips = (concat $ips .Values.whitelist.private_ranges) -}}

{{- if eq $render true -}}
value: {{ $ips | join "," }}
{{- end -}}

{{- end -}}
