{{- if .Values.ingress_enabled }}
{{- with .Values.ingress}}
{{ range $ingress := . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $ingress.name }}
  annotations:
    {{- if $ingress.alb.enabled }}
    alb.ingress.kubernetes.io/group.name: {{ $ingress.alb.groupName | quote }}
    alb.ingress.kubernetes.io/backend-protocol: {{ $ingress.alb.protocol | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ $ingress.alb.listenPorts | quote }}
    alb.ingress.kubernetes.io/scheme: {{ $ingress.alb.scheme }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: 'ip'
    {{- end }}
    {{- with $ingress.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{ end }}
spec:
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if  $ingress.ingressClassName }}
  ingressClassName: {{ $ingress.ingressClassName -}}
  {{ end }}
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
      {{- range $path := $ingress.paths }}
      - pathType: Prefix
        path: {{ $path }}
        backend:
          service:
            name: {{ $.Release.Name }}-{{ $.Chart.Name }}
            port:
              number: {{ $.Values.app.port }}
      {{ end }}
{{ end }}
{{ end }}
{{ end }}