apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  {{- if .Values.labels }}
  labels: {{- .Values.labels | toYaml | nindent 4 -}}
  {{ else }}
  labels:
    app: proxified
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.labels }}
  selector: {{- .Values.labels | toYaml | nindent 4 -}}
  {{ else }}
  selector:
    app: proxified
  {{ end }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: 81
      protocol: TCP
      name: http
