apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Chart.Name }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io
