{{- define "helper.datadog.logs_annotation" -}}

{{/*
Inject the environment environment variables DD_ADMISSION_CONTROLLER_MUTATE_UNLABELLED for the admission controller
https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=helm#apm-and-dogstatsd
*/}}

{{ $datacenter := .Values.global.datacenter }}
{{ $tenant := .Release.Namespace | splitList "-" | first }}
{{ $application := .Release.Name }}
{{ $env := .Release.Namespace | splitList "-" | last }}
{{ $service := .Chart.Name }}
{{ $version := .Values.image | splitList ":" | last }}
{{ $chartVersion := .Values.global.chart_version }}
{{ $containerNameTMP := print .Release.Name "-" .Chart.Name }}
{{ $containerName := default $containerNameTMP .Values.dd_container_name }}
{{ $source := .Values.global.source }}

ad.datadoghq.com/{{ $containerName }}.logs: |
    [
      {
        "source":"{{ $source }}",
        "service":"{{ $service }}"
      }
    ]

ad.datadoghq.com/tags: |
    {
      "datacenter": "{{ $datacenter }}",
      "tenant": "{{ $tenant }}",
      "application": "{{ $application }}",
      "env": "{{ $env }}",
      "service": "{{ $service}}",
      "version": "{{ $version }}",
      "chart_version": "{{ $chartVersion }}",
      "source": "{{ $source }}"
    }
{{- end -}}
