{{/*

Global documentation:
  - DataDog - https://docs.datadoghq.com/
  - ddtrace configuration - https://ddtrace.readthedocs.io/en/stable/configuration.html

*/}}



{{/* Admision controller by annotation | https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=operator#helm */}}
{{ define "helper.datadog.apm.admision_controller" }}

{{ if .Values.datadog.apm.active }}
admission.datadoghq.com/enabled: "true"
{{ end }}

{{ end }}



{{/* Inject library | https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=operator#helm */}}
{{ define "helper.datadog.apm.inject_library" }}

{{ $library := "" }}

{{ if eq .Values.datadog.apm.inject_library.language "js" }}
  {{ $library = "js-lib.version" }}
{{ else if eq .Values.datadog.apm.inject_library.language "python" }}
  {{ $library = "python-lib.version" }}
{{ else if eq .Values.datadog.apm.inject_library.language "ruby" }}
  {{ $library = "ruby-lib.version" }}
{{ end }}

{{ if .Values.datadog.apm.active }}
admission.datadoghq.com/{{ $library }}: {{ .Values.datadog.apm.inject_library.version }}
{{ end }}

{{ end }}



{{/* Active profiler by environment variables | https://docs.datadoghq.com/profiler/enabling/ */}}
{{ define "helper.datadog.apm.profiler" }}

{{ if and .Values.datadog.apm.active .Values.datadog.apm.profiler }}
DD_PROFILING_ENABLED: "true"
{{ else }}
DD_PROFILING_ENABLED: "false"
{{ end }}

DD_ENV: {{ .Release.Namespace | splitList "-" | last }}
DD_SERVICE: {{ .Chart.Name }}
DD_VERSION: {{ .Values.image | splitList ":" | last }}

{{ end }}



{{/* Correlate logs by environment variables | https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/ */}}
{{ define "helper.datadog.apm.correlate_logs" }}

{{ if and .Values.datadog.apm.active .Values.datadog.apm.correlate_logs }}
DD_LOGS_INJECTION: "true"
{{ end }}

{{ end }}



{{/* Trace sample rate by environment variables | https://docs.datadoghq.com/tracing/setup_overview/setup/go/#trace-sample-rate */}}
{{ define "helper.datadog.apm.trace_sample_rate" -}}

{{ if and .Values.datadog.apm.active .Values.datadog.apm.trace_sample_rate.active }}
DD_TRACE_SAMPLE_RATE: {{ .Values.datadog.apm.trace_sample_rate.rate }}
{{ end }}

{{ end }}



{{/* Active apm for go applications | https://docs.datadoghq.com/tracing/setup_overview/setup/go/#instrumentation */}}
{{ define "helper.datadog.apm.go.volumes" }}

{{ if .Values.datadog.apm.active }}
- name: apmsocketpath
  hostPath:
    path: /var/run/datadog/
{{ end }}

{{ end }}

{{ define "helper.datadog.apm.go.volumeMounts" }}

{{ if .Values.datadog.apm.active }}
- name: apmsocketpath
  mountPath: /var/run/datadog
{{ end }}

{{ end }}

{{ define "helper.datadog.apm.go.env" }}

{{ if .Values.datadog.apm.active }}
DD_ENV: "metadata.labels['tags.datadoghq.com/env']"
DD_SERVICE: "metadata.labels['tags.datadoghq.com/service']"
DD_VERSION: "metadata.labels['tags.datadoghq.com/version']"
{{ end }}

{{ end }}
