{{ define "helper.datadog.apm.admision_controller" }}

{{ if .Values.datadog.apm.active }}
admission.datadoghq.com/enabled: "true"
{{ end }}

{{ end }}




{{ define "helper.datadog.apm.inject_library" }}

{{ $library := "" }}

{{ if eq .Values.datadog.apm.inject_library.language "js" }}
  {{ $library = "js-lib.version" }}
{{ else if eq .Values.datadog.apm.inject_library.language "python" }}
  {{ $library = "python-lib.version" }}
{{ else if eq .Values.datadog.apm.inject_library.language "ruby" }}
  {{ $library = "ruby-lib.version" }} 
{{ end }}

{{ if .Values.datadog.apm.active }}
admission.datadoghq.com/{{ $library }}: {{ .Values.datadog.apm.inject_library.version }}
{{ end }}

{{ end }}




{{ define "helper.datadog.apm.profiler" }}

{{ if and .Values.datadog.apm.active .Values.datadog.apm.profiler }}
DD_PROFILING_ENABLED: "true"
{{ else }}
DD_PROFILING_ENABLED: "false"
{{ end }}

DD_ENV: {{ .Release.Namespace | splitList "-" | last }}
DD_SERVICE: {{ .Chart.Name }}
DD_VERSION: {{ .Values.image | splitList ":" | last }}

{{ end }}




{{ define "helper.datadog.apm.correlate_logs" }}

{{ if and .Values.datadog.apm.active .Values.datadog.apm.correlate_logs }}
DD_LOGS_INJECTION: "true"
{{ end }}

{{ end }}




{{ define "helper.datadog.apm.trace_sample_rate" -}}

{{ if and .Values.datadog.apm.active .Values.datadog.apm.trace_sample_rate.active }}
DD_TRACE_SAMPLE_RATE: {{ .Values.datadog.apm.trace_sample_rate.rate }}
DD_TRACE_RATE_LIMIT: {{ default 100 .Values.datadog.apm.trace_sample_rate.limit  }}
{{ end }}

{{ end }}




{{ define "helper.datadog.apm.go.volumes" }}

{{ if .Values.datadog.apm.active }}
- name: apmsocketpath
  hostPath:
    path: /var/run/datadog/
{{ end }}

{{ end }}




{{ define "helper.datadog.apm.go.volumeMounts" }}

{{ if .Values.datadog.apm.active }}
- name: apmsocketpath
  mountPath: /var/run/datadog
{{ end }}

{{ end }}




{{ define "helper.datadog.apm.go.env" }}

{{ if .Values.datadog.apm.active }}
DD_ENV: "metadata.labels['tags.datadoghq.com/env']"
DD_SERVICE: "metadata.labels['tags.datadoghq.com/service']"
DD_VERSION: "metadata.labels['tags.datadoghq.com/version']"
{{ end }}

{{ end }}