{{- define "helper.datadog.labels" -}}
datacenter: {{ .Values.global.datacenter }}
tenant: {{ .Release.Namespace | splitList "-" | first }}
application: {{ .Release.Name }}
tags.datadoghq.com/env: {{ .Release.Namespace | splitList "-" | last }}
tags.datadoghq.com/service: {{ .Chart.Name }}
tags.datadoghq.com/version: {{ .Values.image | splitList ":" | last }}
chart_version: {{ .Values.global.chart_version }}
{{ if .Values.source }}
source: {{ .Values.source }}
{{ else }}
source: {{ .Values.global.source }}
{{ end }}
{{- end -}}
