---
name: aws-web-service-proxified
apiVersion: v2
appVersion: "1.16.0"
description: A Helm chart for Kubernetes to deploy a service proxified via init container with nginx into AWS with alb.
type: application
version: 0.1.0
home: https://github.com/prefapp/charts/tree/master/proxified
icon: https://github.com/prefapp/charts/tree/master/proxified/icon.png
annotations:
  artifacthub.io/links: |
    - name: Support
      url: https://github.com/prefapp/charts/issues
keywords:
  - service
  - generic
  - proxified
  - nginx
sources:
  - https://github.com/prefapp/charts/tree/master/proxified
maintainers:
  - email: gustavo.borragan@prefapp.es
    name: gustavoborragan
  - email: charts@prefapp.es
    name: Info
