apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.app }}
        image: {{ .Values.deployment.image }}
        {{- if .Values.deployment.livenessProbe }}
        livenessProbe:
        {{- with .Values.deployment.livenessProbe }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
        {{- with .Values.deployment.livenessProbe }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        {{- end }}
        volumeMounts:
        {{- if .Values.parameterStore.enabled }}
          - name: parameter-store-volume
            mountPath: /mnt/parameter-store/parameter-store-volume
            readOnly: true
        {{ end }}
        {{- with .Values.deployment.volumeMounts }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
      volumes:
      {{- if .Values.parameterStore.enabled }}
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-spc-ssm
            name: parameter-store-volume
      {{ end }}
      {{- with .Values.deployment.volumes }}
      {{ . | toYaml | nindent 8 }}
      {{- end }}
