apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.deployment.app }}
        image: {{ .Values.webService.image }}
        {{- if .Values.deployment.livenessProbe }}
        livenessProbe:
        {{- with .Values.deployment.livenessProbe }}
        {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
        {{- with .Values.deployment.readinessProbe }}
        {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.startupProbe }}
        startupProbe:
        {{- with .Values.deployment.startupProbe }}
        {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        volumeMounts:
        {{ with .Values.deployment.entrypointFile }}
          - name: {{ $.Release.Name }}-{{ $.Chart.Name }}-command
            mountPath: /entrypoint
            readOnly: true
        {{ end }}
        {{- if .Values.parameterStore.enabled }}
          - name: parameter-store-volume
            mountPath: /mnt/parameter-store/parameter-store-volume
            readOnly: true
        {{- if .Values.parameterStore.mountAsFile }}
          - name: {{ $.Release.Name }}-parameter-store-secrets-file
            mountPath: {{.Values.parameterStore.filePath }}
            readOnly: true
        {{ end }}
        {{ end }}
        {{- with .Values.deployment.volumeMounts }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        {{ if .Values.maintenance_mode | default 0 }}
        command:
          - tail
          - -f
          - /dev/null
        {{- else if .Values.deployment.command }}
        command: {{ .Values.deployment.command | toYaml | nindent 8 }}
        {{- else if .Values.deployment.entrypointFile}}
        command:
          - "sh"
          - "/entrypoint/entrypoint.sh"
        {{ else }}
        command: {}
        {{- end }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        envFrom:
        {{- if and .Values.parameterStore.enabled (eq .Values.parameterStore.mountAsFile false) }}
          - secretRef:
              name: {{ $.Release.Name }}-secret-ssm
        {{ end }}
        {{ with .Values.secrets }}
          - secretRef:
              name: {{ $.Release.Name }}-{{ $.Chart.Name }}
        {{ end }}
        {{ with .Values.configmap }}
          - configMapRef:
              name: {{ $.Release.Name }}-{{ $.Chart.Name }}
        {{ end }}
        {{ with .Values.deployment.entrypointFile }}
          - configMapRef:
              name: {{ $.Release.Name }}-{{ $.Chart.Name }}-command
        {{ end }}
      {{- if .Values.parameterStore.enabled }}
      serviceAccount: {{ .Values.parameterStore.secrets_scm_sa }}
      serviceAccountName: {{ .Values.parameterStore.secrets_scm_sa }}
      {{- end }}
      volumes:
      {{ with .Values.deployment.entrypointFile }}
        - name: {{ $.Release.Name }}-{{ $.Chart.Name }}-command
          configMap:
            name: {{ $.Release.Name }}-{{ $.Chart.Name }}-command
      {{ end }}
      {{- if .Values.parameterStore.enabled }}
        - name: parameter-store-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-{{ .Chart.Name }}-spc-ssm
      {{- if .Values.parameterStore.mountAsFile }}
        - name: {{ $.Release.Name }}-parameter-store-secrets-file
          secret:
            secretName: {{ $.Release.Name }}-secret-ssm
            optional: false
      {{ end }}
      {{ end }}
      {{- with .Values.deployment.volumes }}
      {{ . | toYaml | nindent 8 }}
      {{- end }}
