apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.deployment.app }}
        image: {{ .Values.webService.image }}
        {{- if .Values.deployment.livenessProbe }}
        livenessProbe:
        {{- with .Values.deployment.livenessProbe }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
        {{- with .Values.deployment.livenessProbe }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        {{- end }}
        volumeMounts:
        {{- if .Values.parameterStore.enabled }}
          - name: parameter-store-volume
            mountPath: /mnt/parameter-store/parameter-store-volume
            readOnly: true
        {{ end }}
        {{- with .Values.deployment.volumeMounts }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        {{ if .Values.maintenance_mode | toYaml | nindent 8 }}
        command:
          - tail
          - -f 
          - /dev/null
        {{- end }}
        {{- if .Values.deployment.command }}
        command: {{ .Values.deployment.command | toYaml | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        envFrom:
          - secretRef:
              name: {{ $.Release.Name }}-secret-ssm
        {{ with .Values.secrets }}
          - secretRef:
              name: {{ $.Release.Name }}-{{ $.Chart.Name }}
        {{ end }}
        {{ with .Values.configmap }}
          - configMapRef:
              name: {{ $.Release.Name }}-{{ $.Chart.Name }}
        {{ end }}
      serviceAccount: {{ .Values.parameterStore.secrets_scm_sa }}
      serviceAccountName: {{ .Values.parameterStore.secrets_scm_sa }}
      volumes:
      {{- if .Values.parameterStore.enabled }}
        - name: parameter-store-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-{{ .Chart.Name }}-spc-ssm
      {{ end }}
      {{- with .Values.deployment.volumes }}
      {{ . | toYaml | nindent 8 }}
      {{- end }}
