{{ $ssmConfSplit := .Values.parameterStore.splitter | default "."  }}
---
{{- if and .Values.parameterStore.enabled .Values.parameterStore.mountAsFile }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-spc-ssm-as-file
spec:
  provider: aws
  secretObjects:
  {{ range $key, $value := .Values.parameterStore.dataAsFiles }}
    - secretName: {{ $key }}-{{ .Release.Name }}-secret-ssm
      type: Opaque
      data:
        - objectName: {{ $value.ref | replace $ssmConfSplit  "_" }}
          key: {{ $key }}
  {{ end }}
  parameters:
    objects: |
  {{ range $key, $value := .Values.parameterStore.dataAsFiles }}
      - objectName: {{ $value.ref | quote }}
        objectType: "ssmparameter"
        region: "eu-west-1"
        objectAlias: {{  $value | quote | replace $ssmConfSplit "_" }}
  {{ end }}
{{ end }}
