---
{{- if and .Values.parameterStore.enabled .Values.parameterStore.mountAsFile }}

{{ $ssmConfSplit := .Values.parameterStore.splitter | default "."  }}

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}-spc-ssm-as-file
spec:
  provider: aws
  secretObjects:
  {{ range $key, $value := .Values.parameterStore.dataAsFiles }}
    - secretName: {{ $key }}-{{$.Release.Name}}-secret-ssm
      type: Opaque
      data:
        - objectName: {{ $value.ref | replace $ssmConfSplit  "_" }}
          key: {{ $value.fileName }}
  {{ end }}
  parameters:
    objects: |
  {{ range $key, $value := .Values.parameterStore.dataAsFiles }}
      - objectName: {{ $value.ref | quote }}
        objectType: "ssmparameter"
        region: "eu-west-1"
        objectAlias: {{  $value.ref | quote | replace $ssmConfSplit "_" }}
  {{ end }}
{{ end }}
