{{ $ssmConfSplit := .Values.ssmConfSplit | default "."  }}
---
{{- if .Values.parameterStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-spc-ssm
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Release.Name }}-secret-ssm
      type: Opaque
      data:
      {{ range $key,$value := .Values.secrets.data }}
        - objectName: {{ $value | replace $ssmConfSplit  "_" }}
          key: {{ $key }}
      {{ end }}                 
  parameters:
    objects: |
    {{ range $value := .Values.secrets.data }}
      - objectName: {{ $value | quote }}
        objectType: "ssmparameter"
        region: "eu-west-1"
        objectAlias: {{  $value | quote | replace $ssmConfSplit "_" }}
    {{ end }}
{{ end }}
