apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
  {{ with .Values.service.labels }}
  {{ . | toYaml | nindent 6 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http     

    
