{{- if .Values.parameterStore.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.parameterStore.secrets_scm_sa }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.parameterStore.secrets_scm_sa_arn }}

automountServiceAccountToken: true
{{ end }}
