{{ $scheme := .Values.ingress.alb.scheme | default "internet-facing"  }}
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    {{- if .Values.ingress.alb.enabled }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.alb.groupName | quote }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.alb.protocol | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.alb.listenPorts | quote }}
    alb.ingress.kubernetes.io/scheme: {{ $scheme | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: 'ip'
    {{ end }}
    {{ with .Values.ingress.annotations }}
    {{ . | toYaml | nindent 4 }}
    {{ end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- if kindIs "slice" .hosts }}
      {{- .hosts | toYaml | nindent 6 }}
      {{- else }}
      - {{ .hosts }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{ end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.path }}
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
  {{- with .Values.ingress.extraHosts }}
  {{- range . }}
  - host: {{ .hostPath }}
    http:
      paths:
      - path: {{ .Path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ .name }}
            port:
              number: {{ .Port | default $.Values.service.port }}
  {{- end }}
  {{- end }}
{{ end }}
