{{ if .Values.volume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-pvc
  labels:
    app: {{ .Values.deployment.app }}
    chart: {{ .Chart.Name }}
    env: {{ .Release.Namespace}}
spec:
  volumeName: {{ $.Release.Name }}-{{ $.Chart.Name }}-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.storageSize }}
{{ end }}
