---
{{- if and .Values.parameterStore.enabled (eq .Values.parameterStore.mountAsFile  false)}}
{{ $ssmConfSplit := .Values.parameterStore.splitter | default "."  }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-spc-ssm
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Release.Name }}-secret-ssm
      type: Opaque
      data:
      {{ range $key,$value := .Values.parameterStore.data }}
        - objectName: {{ $value | replace $ssmConfSplit  "_" }}
          key: {{ $key }}
      {{ end }}
  parameters:
    objects: |
    {{ range $value := .Values.parameterStore.data }}
      - objectName: {{ $value | quote }}
        objectType: "ssmparameter"
        region: "eu-west-1"
        objectAlias: {{  $value | quote | replace $ssmConfSplit "_" }}
    {{ end }}
{{ end }}
