{{ with .Values.secrets }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}
data: 
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote | b64enc }}
  {{- end }}

{{ end }}

