apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
  {{ with .Values.service.labels }}
  {{ . | toYaml | nindent 6 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- if .Values.ingress.extraHosts }}
    {{- range $host := .Values.ingress.extraHosts }}
    - port: {{ $host.extraPort | default $.Values.service.port }}
      targetPort: {{ $host.extraPort | default $.Values.service.port }}
      protocol: TCP
      name: http-{{ $host.name }}
    {{- end }}
    {{- end }}

    {{- with .Values.ingresses }}
    {{- range $ingress := . }}
    {{- if $ingress.extraHosts }}
    {{- range $host := $ingress.extraHosts }}
    - port: {{ $host.extraPort | default $.Values.service.port }}
      targetPort: {{ $host.extraPort | default $.Values.service.port }}
      protocol: TCP
      name: http-{{ $host.name }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
