apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}
spec:
  provider:
    azurekv:  
      vaultUrl: "https://{{ .Values.config.keyvaultName }}.vault.azure.net"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: {{ .Release.Name }}
