
{{- define "secret-repo.render" -}}

{{ $ctx := first . }}
{{ $element := last . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $element.name }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ $element.type }}
  url: {{ $element.url }}
{{- end }}

{{ range $k, $v := .Values.repos }}
---
{{ include "secret-repo.render" (list $ $v) }}
{{ end }}
