apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  annotations:
    azure.workload.identity/client-id: '{{ .Values.config.azureIdentity.clientID }}'
    azure.workload.identity/tenant-id: '{{ .Values.config.azureIdentity.tenantID }}'
