---
allowed_operations:
  # Azure
  - aks-start-stop-cluster
  - flexible-server-start-stop-postgresql
  - vmss-scale-instances
  # MongoDB Atlas
  - mongodb-atlas-start-pause-cluster
  # Datadog
  - datadog-unmute-mute-monitors
  # UptimeRobot
  - uptimerobot-resume-pause-monitors
  # Slack
  - slack-notification

global: {}
  # managed_identity:
  #   client_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  #   tenant_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  # subscription_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  # timezone: "Europe/Madrid"

operations: {}
  # # Azure #
  # # AKS #
  # - name: aks-start-stop-cluster
  #   managed_identity: true
  #   cron: "00 19 * * 1-5"
  #   inputs:
  #     resource_group: "group1"
  #     cluster_name: "cluster1"
  #     action: "stop"
  # - name: aks-start-stop-cluster
  #   managed_identity: true
  #   cron: "00 07 * * 1-5"
  #   inputs:
  #     resource_group: "group1"
  #     cluster_name: "cluster1"
  #     action: "start"

  # # Flexible Server PostgreSQL #
  # - name: flexible-server-start-stop-postgresql
  #   managed_identity: true
  #   cron: "00 19 * * 1-5"
  #   inputs:
  #     resource_group: "group2"
  #     server_name: "server1"
  #     action: "stop"
  # - name: flexible-server-start-stop-postgresql
  #   managed_identity: true
  #   cron: "00 07 * * 1-5"
  #   inputs:
  #     resource_group: "group2"
  #     server_name: "server1"
  #     action: "start"
  # - name: flexible-server-start-stop-postgresql
  #   managed_identity: true
  #   cron: "00 19 * * 1-5"
  #   inputs:
  #     resource_group: "group3"
  #     server_name: "server2"
  #     action: "stop"
  # - name: flexible-server-start-stop-postgresql
  #   managed_identity: true
  #   cron: "00 07 * * 1-5"
  #   inputs:
  #     resource_group: "group3"
  #     server_name: "server2"
  #     action: "start"

  # # VMSS #
  # - name: vmss-scale-instances
  #   managed_identity: true
  #   cron: "00 19 * * 1-5"
  #   inputs:
  #     resource_group: "group4"
  #     vmss_name: "vmss1"
  #     instances: 0
  # - name: vmss-scale-instances
  #   managed_identity: true
  #   cron: "00 07 * * 1-5"
  #   inputs:
  #     resource_group: "group4"
  #     vmss_name: "vmss1"
  #     instances: 1

  # # Third Party #
  # # MongoDB Atlas #
  # - name: mongodb-atlas-start-pause-cluster
  #   cron: "00 19 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "mongodb-atlas"
  #     organization_id: "0123456789"
  #     project_id: "proj1"
  #     cluster_name: "cluster2"
  #     action: "pause"
  # - name: mongodb-atlas-start-pause-cluster
  #   cron: "00 07 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "mongodb-atlas"
  #     organization_id: "0123456789"
  #     project_id: "proj1"
  #     cluster_name: "cluster2"
  #     action: "start"

  # # Datadog #
  # - name: datadog-unmute-mute-monitors
  #   cron: "55 18 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "datadog"
  #     monitor_ids:
  #       - "monitor1"
  #       - "monitor2"
  #       - "monitor3"
  #       - "monitor4"
  #       - "monitor5"
  #       - "monitor6"
  #       - "monitor7"
  #       - "monitor8"
  #       - "monitor9"
  #       - "monitor10"
  #     action: mute
  # - name: datadog-unmute-mute-monitors
  #   cron: "20 07 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "datadog"
  #     monitor_ids:
  #       - "monitor1"
  #       - "monitor2"
  #       - "monitor3"
  #       - "monitor4"
  #       - "monitor5"
  #       - "monitor6"
  #       - "monitor7"
  #       - "monitor8"
  #       - "monitor9"
  #       - "monitor10"
  #     action: unmute

  # # UptimeRobot #
  # - name: uptimerobot-resume-pause-monitors
  #   cron: "55 18 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "uptimerobot"
  #     monitor_ids:
  #       - "monitor1"
  #       - "monitor2"
  #       - "monitor3"
  #       - "monitor4"
  #       - "monitor5"
  #       - "monitor6"
  #       - "monitor7"
  #       - "monitor8"
  #       - "monitor9"
  #       - "monitor10"
  #     action: pause
  # - name: uptimerobot-resume-pause-monitors
  #   cron: "20 07 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "uptimerobot"
  #     monitor_ids:
  #       - "monitor1"
  #       - "monitor2"
  #       - "monitor3"
  #       - "monitor4"
  #       - "monitor5"
  #       - "monitor6"
  #       - "monitor7"
  #       - "monitor8"
  #       - "monitor9"
  #       - "monitor10"
  #     action: resume

  # # Slack #
  # - name: slack-notification
  #   cron: "30 19 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "slack-webhook"
  #     operations:
  #       - "aks-group1-cluster1-stop"
  #       - "flexible-group3-server2-stop"
  #       - "flexible-group2-server1-stop"
  #       - "vmss-group4-vmss1-0"
  #       - "mongodb-0123-cluster2-pause"
  #       - "datadog-namespace1-mute"
  #       - "uptimerobot-namespace1-pause"
  # - name: slack-notification
  #   cron: "30 07 * * 1-5"
  #   inputs:
  #     secret_namespace: "namespace1"
  #     secret_name: "slack-webhook"
  #     operations:
  #       - "aks-group1-cluster1-start"
  #       - "flexible-group3-server2-start"
  #       - "flexible-group2-server1-start"
  #       - "vmss-group4-vmss1-1"
  #       - "mongodb-0123-cluster2-start"
  #       - "datadog-namespace1-unmute"
  #       - "uptimerobot-namespace1-resume"
