apiVersion: v2
name: aws-web-service
description: A Helm chart for Kubernetes to deploy a web service using alb annotations and parameter store
type: application
version: 0.1.13
appVersion: "1.0.0"
annotations:
  artifacthub.io/links: |
    - name: Support
      url: https://github.com/prefapp/charts/issues
keywords:
  - aws
  - web
  - service
  - alb
  - parameter-store
  - generic
  - web-service
sources:
  - https://github.com/prefapp/charts/tree/master/aws-web-service

maintainers:
  - email: antonio.rodriguez@prefapp.es
    name: arvegadev
  - email: francisco.maseda@prefapp.es
    name: frmadem
  - email: charts@prefapp.es
    name: Info
