apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    {{ if and .Values.azureIdentity .Values.azureIdentity.enabled }}
    azure.workload.identity/client-id: {{ required ".Values.azureIdentity is required" .Values.azureIdentity.clientID }}
    azure.workload.identity/tenant-id: {{ required ".Values.azureIdentity.tenantID is required" .Values.azureIdentity.tenantID }}
    {{ end }}
