apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    azure.workload.identity/client-id: {{ required ".Values.config.azureIdentity.clientID is required" .Values.config.azureIdentity.clientID }}
    azure.workload.identity/tenant-id: {{ required ".Values.config.azureIdentity.tenantID is required" .Values.config.azureIdentity.tenantID }}
