apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels: {{ .Values.labels | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .Values.labels | toYaml | nindent 8 }}
        azure.workload.identity/use: "true"
        name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Chart.Name }}
      {{ if .Values.imageCredentials }}
      imagePullSecrets:
        - name: {{ $.Release.Name }}-{{ $.Chart.Name }}-ghcr
      {{ end }}
      containers:      
      - name: controller
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "Always" .Values.imagePullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}
          - secretRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-secret-ssm
        
        command: {{ .Values.command | toYaml | nindent 10 }}
        
        volumeMounts:
        - name: csi-secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{ with .Values.extraVolumeMounts }}
        {{ . | toYaml | nindent 10 }}
        {{ end }}

      volumes: 
      - name: csi-secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Release.Name }}-{{ .Chart.Name }}
      {{ with .Values.extraVolumes }}
      {{ . | toYaml | nindent 8 }}
      {{ end }}
