apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Release.Name }}-{{ .Chart.Name }}-secret-ssm
    type: Opaque
    data:
      - objectName: github_app_pem_file
        key: GITHUB_APP_PEM_FILE
  parameters:
    tenantId: {{ .Values.config.azureIdentity.tenantID }}
    usePodIdentity: "false"
    clientID: {{ .Values.config.azureIdentity.clientID }}
    keyvaultName: {{ .Values.config.keyvaultName }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: {{ .Values.config.githubApp.pemSecretRef }}
          objectType: secret
          objectVersion: ""
          objectAlias: "github_app_pem_file"

    {{- with .Values.extraSecretProviderClass }}
    {{ . | toYaml | nindent 2 }}
    {{- end }}
