apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://{{ .Values.config.keyvaultName }}.vault.azure.net/"
      serviceAccountRef:
        name: {{ .Release.Name }}-{{ .Chart.Name }}
