{{ define "helper.csi-secrets-driver.sa-az" -}}
{{ range $key, $value := .Values.serviceAccount.annotations -}}
{{ $key }}: {{ $value }}
{{ end -}}
{{ $managedIdentity := coalesce .Values.managedIdentity .Values.global.managedIdentity -}}
{{ if $managedIdentity.tenantId -}}
azure.workload.identity/tenant-id: {{ $managedIdentity.tenantId -}}
{{ end }}
{{ if $managedIdentity.clientId -}}
azure.workload.identity/client-id: {{ $managedIdentity.clientId -}}
{{ end -}}
{{ end }}
