{{ define "helper.csi-secrets-driver.az-kv" }}
{{- range $index, $element := .Values.kvSecrets }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $element.kv }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ $.Release.Name }}-{{ $.Chart.Name }}-secret-ssm
    type: Opaque
    data:
    {{- range $key, $value := $element.data }}
      {{ $key | upper }}: {{ $value }}
    {{- end }}
  parameters:
    tenantId: {{ $.Values.csiSecretsStoreConfig.tenantId }}
    usePodIdentity: "false"
    clientID: {{ $.Values.csiSecretsStoreConfig.clientId }}
    keyvaultName: {{ $element.kv }}
    cloudName: ""
    objects: |
      array:
      {{- range $key, $value := $element.data }}
        - |
          objectName: {{ $key | upper }}
          objectType: secret
          objectVersion: ""
          objectAlias: {{ $value }}
      {{- end }}
{{- end }}
{{ end }}


