{{ define "helper.csi-secrets-driver.az-kv" }}
{{- range $index, $element := .Values.kvSecrets }}
{{ $managedIdentity := coalesce $.Values.managedIdentity $.Values.global.managedIdentity }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $element.kv }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ $.Release.Name }}-{{ $.Chart.Name }}-secret-ssm-{{ $element.kv }}
    type: Opaque
    data:
    {{- range $key, $value := $element.data }}
      - key: {{ $key }}
        objectName: {{ $value }}
    {{- end }}
  parameters:
    tenantId: {{ $managedIdentity.tenantId }}
    usePodIdentity: "false"
    clientID: {{ $managedIdentity.clientId }}
    keyvaultName: {{ $element.kv }}
    cloudName: ""
    objects: |
      array:
      {{- range $key, $value := $element.data }}
        - |
          objectName: {{ $value }}
          objectType: secret
          objectVersion: ""
          objectAlias: {{ $value }}
      {{- end }}
{{- end }}
{{ end }}
