{{ define "csi-secrets-store-helpers.env_from_secret" }}
{{- range $index, $element := .Values.kvSecrets }}
- secretRef: 
    name: {{ $.Release.Name }}-{{ $.Chart.Name }}-secret-ssm-{{ $element.kv }}
{{- end }}
{{- end }}
