name: Pr verify

on:
  pull_request:

jobs:
  pr-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: npm-install
        run: npm install

      - name: Unit-Test
        run: npm run test
